### ISSUE TITLE
Error when installing!

### ISSUE THREAD

**Issue by jdHehe** [CoinCulture/evm-tools#6]
go-ethereum version:1.8
OS: win7

description: I met a  error when do 'make'  following the doc .
error info:
evm\main.go:38:2: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:

I guess the version  of go-ethereum on my machine may be wrong. So i try release-1.5 again.Error happen again. 
error-2 info:
evm\main.go:116:13: statedb.HasAccount undefined (type *state.StateDB has no field or method HasAccount)
evm\main.go:130:13: chainConfig.VmConfig undefined (type *params.ChainConfig has no field or method VmConfig)
evm\main.go:140:31: not enough arguments in call to core.NewBlockChain
        have (*ethdb.MemDatabase, *params.ChainConfig, core.FakePow, *event.TypeMux)
        want (ethdb.Database, *params.ChainConfig, pow.PoW, *event.TypeMux, vm.Config)
.............................

So, which version of go-ethereum should I choose!!
ThankU first!

**Comment by ebuchman** [comment]
Did you use glide to install the dependencies?

I just updated the repo to use `dep` instead of `glide` and moved the installation instructions into their own file: https://github.com/CoinCulture/evm-tools/blob/master/INSTALL.md

Can you try the instructions there? 

Namely, pull the latest version of this repo and run `dep ensure` and then `make`. That should work.

Please open a new issue if it doesn't. Thanks!
